name: Build and Release
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        distribution: temurin
      java-version: "11"
  - name: Make gradlew executable
    run: chmod +x ./gradlew
  - name: Build APK
    run: bash ./gradlew assembleDebug
  - name: Upload APK
    uses: actions/upload-artifact@v1
    with:
      name: apk
      path: app/build/outputs/apk/debug/app-debug.apk
